### ISSUE TITLE
Crashes when using reconstruct-symbols switch

### ISSUE THREAD

**Issue by AntonKukoba1** [jnider/delinker#3]
Tried to unlink ps binary into .o files:

> ~/Desktop/delinker $ ./delinker ps --reconstruct-symbols
> registering backend pe32
> registering backend elf32
> registering backend elf64
> 64-bit ELF header
> Little endian
> Version: 1
> OS: SystemV
> Type: Executable
> Machine: x86-64 (62)
> Entry point: 0x402f10
> Number of program headers: 9
> Number of section headers: 29
> Size of section headers: 64
> String table index: 28
> Can't find string table section!
> ELF64 loading done (0 symbols, 0 relocs)
> reconstructing symbols from text section
> found entry point source.c @ 0x0 - renaming to 'main'
> 180 symbols recovered
> Building relocations
> Done building relocations
> Segmentation fault

**Comment by jnider** [comment]
Any chance you can share the binary with me so I can debug it?

**Comment by jnider** [comment]
Did you mean /bin/ps ?

**Comment by AntonKukoba1** [comment]
yep I meant /bin/ps. I've used the one from linux mint 18 x64.

**Comment by jnider** [comment]
I fixed the crash (trying to dereference a NULL pointer) but the program will still not work as expected since it does not yet support 64-bit ELF as an input file.  There are a few more changes that need to be made - but at least it doesn't crash now. I will have to first enable disassembly in 64-bit mode, then update the list of instructions that need to be delinked.

**Comment by jnider** [comment]
There is now some support for x86_64 ELF. It can recreate the symbols, create the relocations and outputs a single object file "source.o".
However, this .o file cannot yet be successfully relinked because some of the relocations (of the the dynamic symbols) seem to be of the wrong type. I tested this on "/bin/ps" from Ubuntu 20.04 because that's what I have.

**Comment by AntonKukoba1** [comment]
Yes it works now https://pastebin.com/CzmAC5yF thank you.
